# Generated by Django 4.0.3 on 2022-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('supplier', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('unit', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
