# Generated by Django 4.0.3 on 2022-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
