# Generated by Django 4.0.3 on 2022-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_details_phone_number_alter_details_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='location',
            field=models.TextField(max_length=100),
        ),
    ]
