# Generated by Django 4.0.3 on 2022-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_details_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='cDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=50)),
                ('cemail', models.EmailField(max_length=60)),
                ('cphone_number', models.IntegerField()),
                ('clocation', models.TextField(max_length=100)),
            ],
        ),
    ]
